#!/bin/bash

# restart the process if dead
check_zombie() {
	if systemctl status $1 | grep "inactive"; then
		systemctl start $1
		echo "> restarted $1"
	fi
}

echo Checking for zombies...
while true; do
	check_zombie mysql
	check_zombie apache2

	sleep 10
done

